name: Azure Databricks VNET Injection deployment

trigger: 
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self  

- task: AzureCLI@2
  displayName: Deploy ARM Templates for ADB
  inputs:
    azureSubscription: 'srgolla subscription connection'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: | 
             
              az deployment group create --resource-group "Network-RG-EastUS2" --name network-eastus2 --template-file pattern-datafactory-databricks/components/databricks-templates/adbnsg.json --parameters pattern-datafactory-databricks/components/databricks-templates/adbnsg.parameters.json
              az deployment group create --resource-group "Network-RG-EastUS2" --name VNET injection  --template-file pattern-datafactory-databricks/components/databricks-templates/adbvnetinjection.json --parameters pattern-datafactory-databricks/components/databricks-templates/adbvnetinjection.parameters.json
              az deployment group create --resource-group "Network-RG-EastUS2"  --template-file --template-file pattern-datafactory-databricks/components/databricks-templates/azure-databricks.json --parameters pattern-datafactory-databricks/components/databricks-templates/azure-databricks.parameters.json
              