name: ADF deployment

trigger: 
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self  

- task: AzureCLI@2
  displayName: Deploy ARM Templates
  inputs:
    azureSubscription: 'srgolla subscription connection'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: | 
   
       az deployment group create --resource-group network-eastus2-rg --name network-eastus2 --template-file pattern-functions-servicebus/components/base-network/azuredeploy.json --parameters hubVnetPrefix="10.0.0.0/16" firewallSubnetPrefix="10.0.1.0/24" DNSSubnetPrefix="10.0.2.0/24" spokeVnetPrefix="10.1.0.0/16" workloadSubnetPrefix="10.1.2.0/24"
